export type BlockCategory="motion"|"looks"|"sound"|"events"|"control"|"sensing"|"operators"|"variables";
export type BlockType="statement"|"reporter"|"boolean"|"hat"|"cap";
export type BlockParameterKind="number"|"string"|"select";
export type BlockParameterOption={label:string;value:string};
export type BlockParameter={id:string;label:string;value:string;kind?:BlockParameterKind;options?:BlockParameterOption[];placeholder?:string};
export type BlockSectionDefinition={id:string;label:string;emptyLabel?:string};
export type BlockDefinition={id:string;category:BlockCategory;type:BlockType;name:string;parameters:BlockParameter[];color:string;sections?:BlockSectionDefinition[]};
export type BlockCatalogEntry=BlockDefinition&{description:string};
export type WorkspaceBlockSection=BlockSectionDefinition&{blocks:WorkspaceBlock[]};
export type WorkspaceBlock=Omit<BlockCatalogEntry,"parameters"|"sections">&{instanceId:string;parameters:BlockParameter[];sections:WorkspaceBlockSection[];comment?:string};
export type WorkspaceDropTarget={parentInstanceId:string|null;sectionId:string|null;index:number};
type WorkspaceLookup={block:WorkspaceBlock;parentInstanceId:string|null;sectionId:string|null;index:number;ancestry:string[]};
type WorkspaceDetachResult={removed:WorkspaceBlock|null;nextBlocks:WorkspaceBlock[];parentInstanceId:string|null;sectionId:string|null;index:number};
export const orderedBlockCategories:BlockCategory[]=["motion","looks","sound","events","control","sensing","operators","variables"];
export const blockCategoryMeta:Record<BlockCategory,{label:string;color:string;panelClassName:string;textClassName:string}>= {motion:{label:"Движение",color:"#4C97FF",panelClassName:"border-[#cfe2ff] bg-[#edf5ff]",textClassName:"text-white"},looks:{label:"Внешность",color:"#9966FF",panelClassName:"border-[#e1d5ff] bg-[#f5f1ff]",textClassName:"text-white"},sound:{label:"Звук",color:"#CF63CF",panelClassName:"border-[#f0d1f0] bg-[#fff2ff]",textClassName:"text-white"},events:{label:"События",color:"#FFD500",panelClassName:"border-[#ffe8a8] bg-[#fff9d9]",textClassName:"text-[#5a4700]"},control:{label:"Управление",color:"#FFAB19",panelClassName:"border-[#ffdca6] bg-[#fff5e3]",textClassName:"text-[#5b3300]"},sensing:{label:"Сенсоры",color:"#5CB1D6",panelClassName:"border-[#c9e7f4] bg-[#ecf8ff]",textClassName:"text-white"},operators:{label:"Операторы",color:"#59C059",panelClassName:"border-[#cbeccb] bg-[#effbef]",textClassName:"text-white"},variables:{label:"Переменные",color:"#FF4C4C",panelClassName:"border-[#ffc8c8] bg-[#fff1f1]",textClassName:"text-white"}};
const commonKeys:BlockParameterOption[]=[{label:"пробел",value:"пробел"},{label:"стрелка вверх",value:"стрелка вверх"},{label:"стрелка вниз",value:"стрелка вниз"},{label:"стрелка влево",value:"стрелка влево"},{label:"стрелка вправо",value:"стрелка вправо"},{label:"A",value:"A"}];
const spriteOptions:BlockParameterOption[]=[{label:"Sprite 1",value:"Sprite 1"},{label:"Sprite 2",value:"Sprite 2"},{label:"указатель мыши",value:"указатель мыши"}];
const costumeOptions:BlockParameterOption[]=[{label:"костюм 1",value:"костюм 1"},{label:"костюм 2",value:"костюм 2"},{label:"случайный",value:"случайный"}];
const soundOptions:BlockParameterOption[]=[{label:"pop",value:"pop"},{label:"meow",value:"meow"},{label:"beep",value:"beep"}];
const rotationStyleOptions:BlockParameterOption[]=[{label:"все направления",value:"все направления"},{label:"влево-вправо",value:"влево-вправо"},{label:"не вращать",value:"не вращать"}];
const variableOptions:BlockParameterOption[]=[{label:"счёт",value:"счёт"},{label:"жизни",value:"жизни"},{label:"уровень",value:"уровень"}];
const booleanOptions:BlockParameterOption[]=[{label:"истина",value:"истина"},{label:"ложь",value:"ложь"}];
const controlConditionOptions:BlockParameterOption[]=[{label:"касается края?",value:"касается края?"},{label:"мышь нажата?",value:"мышь нажата?"},{label:"клавиша пробел нажата?",value:"клавиша пробел нажата?"},{label:"таймер > 10",value:"таймер > 10"}];
const numberParameter=(id:string,label:string,value:string,placeholder?:string):BlockParameter=>({id,label,value,kind:"number",placeholder});
const stringParameter=(id:string,label:string,value:string,placeholder?:string):BlockParameter=>({id,label,value,kind:"string",placeholder});
const selectParameter=(id:string,label:string,value:string,options:BlockParameterOption[]):BlockParameter=>({id,label,value,kind:"select",options});
const stackSection=(id:string,label:string,emptyLabel:string):BlockSectionDefinition=>({id,label,emptyLabel});
const block=(entry:Omit<BlockCatalogEntry,"color">&{category:BlockCategory}):BlockCatalogEntry=>({...entry,color:blockCategoryMeta[entry.category].color});
export const blockCatalog:BlockCatalogEntry[]=[
block({id:"motion-move",category:"motion",type:"statement",name:"идти",parameters:[numberParameter("steps","шагов","10")],description:"Перемещает спрайт вперёд на указанное число шагов."}),
block({id:"motion-turn-left",category:"motion",type:"statement",name:"повернуть влево",parameters:[numberParameter("degrees","градусов","15")],description:"Поворачивает спрайт влево на выбранный угол."}),
block({id:"motion-turn-right",category:"motion",type:"statement",name:"повернуть вправо",parameters:[numberParameter("degrees","градусов","15")],description:"Поворачивает спрайт вправо на выбранный угол."}),
block({id:"motion-go-to",category:"motion",type:"statement",name:"перейти в",parameters:[numberParameter("x","x","0"),numberParameter("y","y","0")],description:"Сразу переносит спрайт в указанные координаты."}),
block({id:"motion-glide-to",category:"motion",type:"statement",name:"плавно переместиться",parameters:[numberParameter("seconds","секунд","1"),numberParameter("x","x","0"),numberParameter("y","y","0")],description:"Перемещает спрайт к точке x/y за выбранное время."}),
block({id:"motion-point-direction",category:"motion",type:"statement",name:"установить направление",parameters:[numberParameter("direction","градусов","90")],description:"Задаёт направление, в котором смотрит спрайт."}),
block({id:"motion-rotation-style",category:"motion",type:"statement",name:"стиль вращения",parameters:[selectParameter("style","стиль","все направления",rotationStyleOptions)],description:"Меняет способ вращения спрайта на сцене."}),
block({id:"motion-x-position",category:"motion",type:"reporter",name:"координата x",parameters:[],description:"Возвращает текущую координату X активного спрайта."}),
block({id:"motion-y-position",category:"motion",type:"reporter",name:"координата y",parameters:[],description:"Возвращает текущую координату Y активного спрайта."}),
block({id:"looks-switch-costume",category:"looks",type:"statement",name:"сменить костюм на",parameters:[selectParameter("costume","костюм","костюм 1",costumeOptions)],description:"Переключает спрайт на выбранный костюм."}),
block({id:"looks-next-costume",category:"looks",type:"statement",name:"следующий костюм",parameters:[],description:"Переключает спрайт на следующий костюм по порядку."}),
block({id:"looks-say",category:"looks",type:"statement",name:"сказать",parameters:[stringParameter("message","текст","Привет!","Введите фразу"),numberParameter("seconds","секунд","2")],description:"Показывает облачко речи с текстом на несколько секунд."}),
block({id:"looks-think",category:"looks",type:"statement",name:"думать",parameters:[stringParameter("message","текст","Хм...","Введите мысль")],description:"Показывает облачко мысли над спрайтом."}),
block({id:"looks-change-size",category:"looks",type:"statement",name:"изменить размер на",parameters:[numberParameter("delta","пунктов","10")],description:"Увеличивает или уменьшает размер спрайта."}),
block({id:"looks-set-size",category:"looks",type:"statement",name:"установить размер",parameters:[numberParameter("size","%","100")],description:"Устанавливает размер спрайта в процентах."}),
block({id:"looks-show",category:"looks",type:"statement",name:"показаться",parameters:[],description:"Делает спрайт видимым на сцене."}),
block({id:"looks-hide",category:"looks",type:"statement",name:"спрятаться",parameters:[],description:"Скрывает спрайт со сцены."}),
block({id:"looks-costume-number",category:"looks",type:"reporter",name:"номер костюма",parameters:[],description:"Возвращает порядковый номер текущего костюма."}),
block({id:"sound-play",category:"sound",type:"statement",name:"играть звук",parameters:[selectParameter("sound","звук","pop",soundOptions)],description:"Запускает выбранный звук."}),
block({id:"sound-stop",category:"sound",type:"statement",name:"остановить все звуки",parameters:[],description:"Мгновенно останавливает все воспроизводимые звуки."}),
block({id:"sound-change-volume",category:"sound",type:"statement",name:"изменить громкость на",parameters:[numberParameter("delta","%","10")],description:"Изменяет громкость относительно текущего значения."}),
block({id:"sound-set-volume",category:"sound",type:"statement",name:"установить громкость",parameters:[numberParameter("volume","%","100")],description:"Устанавливает конкретный уровень громкости."}),
block({id:"sound-volume",category:"sound",type:"reporter",name:"громкость",parameters:[],description:"Возвращает текущее значение громкости."}),
block({id:"event-flag",category:"events",type:"hat",name:"при нажатии зелёного флага",parameters:[],description:"Запускает скрипт, когда нажимают зелёный флаг."}),
block({id:"event-key",category:"events",type:"hat",name:"при нажатии клавиши",parameters:[selectParameter("key","клавиша","пробел",commonKeys)],description:"Запускает скрипт при нажатии выбранной клавиши."}),
block({id:"event-sprite-clicked",category:"events",type:"hat",name:"при щелчке по спрайту",parameters:[],description:"Запускает скрипт, когда пользователь кликает по спрайту."}),
block({id:"event-broadcast",category:"events",type:"statement",name:"передать сообщение",parameters:[selectParameter("message","сообщение","message1",[{label:"message1",value:"message1"},{label:"start",value:"start"},{label:"finish",value:"finish"}])],description:"Отправляет событие другим скриптам."}),
block({id:"event-when-received",category:"events",type:"hat",name:"когда я получу сообщение",parameters:[selectParameter("message","сообщение","message1",[{label:"message1",value:"message1"},{label:"start",value:"start"},{label:"finish",value:"finish"}])],description:"Запускает скрипт, когда приходит выбранное сообщение."}),
block({id:"control-wait",category:"control",type:"statement",name:"ждать",parameters:[numberParameter("seconds","секунд","1")],description:"Приостанавливает выполнение скрипта на выбранное время."}),
block({id:"control-repeat",category:"control",type:"statement",name:"повторить",parameters:[numberParameter("times","раз","10")],sections:[stackSection("body","Повторяемые команды","Перетащи команды в цикл")],description:"Повторяет вложенные команды указанное количество раз."}),
block({id:"control-forever",category:"control",type:"statement",name:"всегда",parameters:[],sections:[stackSection("body","Команды цикла","Перетащи команды в бесконечный цикл")],description:"Бесконечно выполняет вложенные команды."}),
block({id:"control-if",category:"control",type:"statement",name:"если",parameters:[selectParameter("condition","условие","касается края?",controlConditionOptions)],sections:[stackSection("if","Если условие истинно","Перетащи команды для ветки «если»")],description:"Выполняет вложенные команды, только если условие истинно."}),
block({id:"control-if-else",category:"control",type:"statement",name:"если иначе",parameters:[selectParameter("condition","условие","касается края?",controlConditionOptions)],sections:[stackSection("if","Если условие истинно","Перетащи команды для ветки «если»"),stackSection("else","Иначе","Перетащи команды для ветки «иначе»")],description:"Хранит две отдельные ветки команд для условий true и false."}),
block({id:"control-wait-until",category:"control",type:"statement",name:"ждать до",parameters:[selectParameter("condition","условие","мышь нажата?",controlConditionOptions)],description:"Ожидает, пока условие не станет истинным."}),
block({id:"control-repeat-until",category:"control",type:"statement",name:"повторять до",parameters:[selectParameter("condition","условие","касается края?",controlConditionOptions)],sections:[stackSection("body","Команды цикла","Перетащи команды, которые нужно повторять")],description:"Выполняет вложенные команды до тех пор, пока условие не станет истинным."}),
block({id:"control-stop",category:"control",type:"cap",name:"остановить",parameters:[selectParameter("target","что","этот скрипт",[{label:"этот скрипт",value:"этот скрипт"},{label:"всё",value:"всё"}])],description:"Завершает текущий скрипт или останавливает всю программу."}),
block({id:"sensing-touching-mouse",category:"sensing",type:"boolean",name:"касается указателя мыши?",parameters:[],description:"Проверяет, касается ли спрайт указателя мыши."}),
block({id:"sensing-touching-edge",category:"sensing",type:"boolean",name:"касается края?",parameters:[],description:"Проверяет, касается ли спрайт края сцены."}),
block({id:"sensing-touching-sprite",category:"sensing",type:"boolean",name:"касается спрайта?",parameters:[selectParameter("target","спрайт","Sprite 2",spriteOptions)],description:"Проверяет соприкосновение с другим спрайтом."}),
block({id:"sensing-mouse-x",category:"sensing",type:"reporter",name:"координата мыши x",parameters:[],description:"Возвращает координату курсора по оси X."}),
block({id:"sensing-mouse-y",category:"sensing",type:"reporter",name:"координата мыши y",parameters:[],description:"Возвращает координату курсора по оси Y."}),
block({id:"sensing-mouse-down",category:"sensing",type:"boolean",name:"мышь нажата?",parameters:[],description:"Сообщает, нажата ли кнопка мыши."}),
block({id:"sensing-key-pressed",category:"sensing",type:"boolean",name:"нажата клавиша?",parameters:[selectParameter("key","клавиша","пробел",commonKeys)],description:"Проверяет, нажата ли выбранная клавиша."}),
block({id:"sensing-ask-and-wait",category:"sensing",type:"statement",name:"спросить и ждать",parameters:[stringParameter("question","вопрос","Как тебя зовут?","Введите вопрос")],description:"Показывает вопрос и ждёт ответ пользователя."}),
block({id:"sensing-answer",category:"sensing",type:"reporter",name:"ответ",parameters:[],description:"Возвращает последний ответ пользователя."}),
block({id:"sensing-timer",category:"sensing",type:"reporter",name:"таймер",parameters:[],description:"Показывает текущее значение таймера."}),
block({id:"sensing-reset-timer",category:"sensing",type:"statement",name:"сбросить таймер",parameters:[],description:"Сбрасывает таймер и начинает отсчёт заново."}),
block({id:"operator-add",category:"operators",type:"reporter",name:"+",parameters:[numberParameter("left","A","1"),numberParameter("right","B","1")],description:"Складывает два значения."}),
block({id:"operator-subtract",category:"operators",type:"reporter",name:"-",parameters:[numberParameter("left","A","10"),numberParameter("right","B","1")],description:"Вычитает одно значение из другого."}),
block({id:"operator-multiply",category:"operators",type:"reporter",name:"*",parameters:[numberParameter("left","A","2"),numberParameter("right","B","3")],description:"Умножает два значения."}),
block({id:"operator-divide",category:"operators",type:"reporter",name:"/",parameters:[numberParameter("left","A","10"),numberParameter("right","B","2")],description:"Делит одно значение на другое."}),
block({id:"operator-random",category:"operators",type:"reporter",name:"случайное от",parameters:[numberParameter("from","от","1"),numberParameter("to","до","10")],description:"Возвращает случайное число из диапазона."}),
block({id:"operator-greater",category:"operators",type:"boolean",name:">",parameters:[numberParameter("left","A","10"),numberParameter("right","B","5")],description:"Проверяет, больше ли первое значение второго."}),
block({id:"operator-less",category:"operators",type:"boolean",name:"<",parameters:[numberParameter("left","A","3"),numberParameter("right","B","8")],description:"Проверяет, меньше ли первое значение второго."}),
block({id:"operator-equals",category:"operators",type:"boolean",name:"=",parameters:[stringParameter("left","A","текст"),stringParameter("right","B","текст")],description:"Сравнивает два значения на равенство."}),
block({id:"operator-and",category:"operators",type:"boolean",name:"и",parameters:[selectParameter("left","A","истина",booleanOptions),selectParameter("right","B","ложь",booleanOptions)],description:"Возвращает истину только если оба условия истинны."}),
block({id:"operator-or",category:"operators",type:"boolean",name:"или",parameters:[selectParameter("left","A","истина",booleanOptions),selectParameter("right","B","ложь",booleanOptions)],description:"Возвращает истину, если хотя бы одно условие истинно."}),
block({id:"operator-not",category:"operators",type:"boolean",name:"не",parameters:[selectParameter("value","значение","ложь",booleanOptions)],description:"Инвертирует логическое значение."}),
block({id:"operator-join",category:"operators",type:"reporter",name:"объединить строки",parameters:[stringParameter("left","A","Привет"),stringParameter("right","B","мир")],description:"Склеивает две строки в одну."}),
block({id:"operator-letter",category:"operators",type:"reporter",name:"буква",parameters:[numberParameter("index","номер","1"),stringParameter("text","строка","Scratch")],description:"Возвращает символ с указанной позиции в строке."}),
block({id:"operator-length",category:"operators",type:"reporter",name:"длина строки",parameters:[stringParameter("text","строка","Scratch")],description:"Возвращает длину указанной строки."}),
block({id:"operator-mod",category:"operators",type:"reporter",name:"остаток от деления",parameters:[numberParameter("left","A","10"),numberParameter("right","B","3")],description:"Возвращает остаток от деления одного числа на другое."}),
block({id:"operator-round",category:"operators",type:"reporter",name:"округлить",parameters:[numberParameter("value","число","3.14")],description:"Округляет число до ближайшего целого."}),
block({id:"variable-create",category:"variables",type:"statement",name:"создать переменную",parameters:[stringParameter("name","имя","новая переменная","Введите имя переменной")],description:"Описывает создание новой переменной в проекте."}),
block({id:"variable-set",category:"variables",type:"statement",name:"установить значение",parameters:[selectParameter("variable","переменная","счёт",variableOptions),stringParameter("value","значение","0")],description:"Записывает новое значение в переменную."}),
block({id:"variable-change",category:"variables",type:"statement",name:"изменить на",parameters:[selectParameter("variable","переменная","счёт",variableOptions),numberParameter("delta","число","1")],description:"Увеличивает или уменьшает значение переменной."}),
block({id:"variable-show",category:"variables",type:"statement",name:"показать переменную",parameters:[selectParameter("variable","переменная","счёт",variableOptions)],description:"Показывает монитор выбранной переменной на сцене."}),
block({id:"variable-hide",category:"variables",type:"statement",name:"скрыть переменную",parameters:[selectParameter("variable","переменная","счёт",variableOptions)],description:"Скрывает монитор выбранной переменной."}),
block({id:"variable-value",category:"variables",type:"reporter",name:"значение переменной",parameters:[selectParameter("variable","переменная","счёт",variableOptions)],description:"Возвращает текущее значение выбранной переменной."})
];
export function filterBlocksByName(blocks:BlockCatalogEntry[],query:string){const normalizedQuery=query.trim().toLocaleLowerCase("ru-RU");if(!normalizedQuery){return blocks;}return blocks.filter((block)=>block.name.toLocaleLowerCase("ru-RU").includes(normalizedQuery));}
export function groupBlocksByCategory(blocks:BlockCatalogEntry[]){return orderedBlockCategories.map((category)=>({category,meta:blockCategoryMeta[category],blocks:blocks.filter((block)=>block.category===category)}));}
export function createInstanceId(blockId:string){if(typeof crypto!=="undefined"&&"randomUUID" in crypto){return `${blockId}-${crypto.randomUUID()}`;}return `${blockId}-${Math.random().toString(16).slice(2,10)}`;}
export function createWorkspaceBlock(block:BlockCatalogEntry):WorkspaceBlock{return {...block,instanceId:createInstanceId(block.id),parameters:block.parameters.map((parameter)=>({...parameter})),sections:(block.sections||[]).map((section)=>({...section,blocks:[]}))};}
export function cloneWorkspaceBlock(block:WorkspaceBlock):WorkspaceBlock{return {...block,instanceId:createInstanceId(block.id),parameters:block.parameters.map((parameter)=>({...parameter})),sections:block.sections.map((section)=>({...section,blocks:section.blocks.map((child)=>cloneWorkspaceBlock(child))}))};}
export function countWorkspaceBlocks(blocks:WorkspaceBlock[]):number{return blocks.reduce((total,block)=>total+1+block.sections.reduce((sectionTotal,section)=>sectionTotal+countWorkspaceBlocks(section.blocks),0),0);}
export function insertWorkspaceBlock<T>(blocks:T[],block:T,targetIndex:number){const safeIndex=Math.min(Math.max(targetIndex,0),blocks.length);const next=[...blocks];next.splice(safeIndex,0,block);return next;}
export function moveWorkspaceBlock<T extends {instanceId:string}>(blocks:T[],instanceId:string,targetIndex:number){const sourceIndex=blocks.findIndex((block)=>block.instanceId===instanceId);if(sourceIndex===-1){return blocks;}const safeIndex=Math.min(Math.max(targetIndex,0),blocks.length);const next=[...blocks];const [moved]=next.splice(sourceIndex,1);const adjustedIndex=sourceIndex<safeIndex?safeIndex-1:safeIndex;next.splice(adjustedIndex,0,moved);return next;}
function findWorkspaceBlockInternal(blocks:WorkspaceBlock[],instanceId:string,parentInstanceId:string|null=null,sectionId:string|null=null,ancestry:string[]=[]):WorkspaceLookup|null{for(const [index,block] of blocks.entries()){if(block.instanceId===instanceId){return {block,parentInstanceId,sectionId,index,ancestry};}for(const section of block.sections){const nested=findWorkspaceBlockInternal(section.blocks,instanceId,block.instanceId,section.id,[...ancestry,block.instanceId]);if(nested){return nested;}}}return null;}
export function findWorkspaceBlock(blocks:WorkspaceBlock[],instanceId:string){return findWorkspaceBlockInternal(blocks,instanceId);}
function workspaceSubtreeContains(block:WorkspaceBlock,instanceId:string):boolean{if(block.instanceId===instanceId){return true;}return block.sections.some((section)=>section.blocks.some((child)=>workspaceSubtreeContains(child,instanceId)));}
function detachWorkspaceBlockInternal(blocks:WorkspaceBlock[],instanceId:string,parentInstanceId:string|null=null,sectionId:string|null=null):WorkspaceDetachResult{const index=blocks.findIndex((block)=>block.instanceId===instanceId);if(index>=0){return {removed:blocks[index],nextBlocks:blocks.filter((block)=>block.instanceId!==instanceId),parentInstanceId,sectionId,index};}for(const block of blocks){for(const section of block.sections){const nested=detachWorkspaceBlockInternal(section.blocks,instanceId,block.instanceId,section.id);if(nested.removed){return {removed:nested.removed,parentInstanceId:nested.parentInstanceId,sectionId:nested.sectionId,index:nested.index,nextBlocks:blocks.map((item)=>item.instanceId===block.instanceId?{...item,sections:item.sections.map((itemSection)=>itemSection.id===section.id?{...itemSection,blocks:nested.nextBlocks}:itemSection)}:item)};}}}return {removed:null,nextBlocks:blocks,parentInstanceId:null,sectionId:null,index:-1};}
function insertIntoWorkspace(blocks:WorkspaceBlock[],target:WorkspaceDropTarget,block:WorkspaceBlock):WorkspaceBlock[]|null{if(!target.parentInstanceId){return insertWorkspaceBlock(blocks,block,target.index);}let found=false;const next=blocks.map((item)=>{if(item.instanceId===target.parentInstanceId){const nextSections=item.sections.map((section)=>{if(section.id!==target.sectionId){return section;}found=true;return {...section,blocks:insertWorkspaceBlock(section.blocks,block,target.index)};});return found?{...item,sections:nextSections}:item;}let sectionChanged=false;const nextSections=item.sections.map((section)=>{const nested=insertIntoWorkspace(section.blocks,target,block);if(!nested){return section;}found=true;sectionChanged=true;return {...section,blocks:nested};});return sectionChanged?{...item,sections:nextSections}:item;});return found?next:null;}
export function removeWorkspaceBlockTree(blocks:WorkspaceBlock[],instanceId:string){return detachWorkspaceBlockInternal(blocks,instanceId).nextBlocks;}
export function updateWorkspaceBlockTree(blocks:WorkspaceBlock[],instanceId:string,updater:(block:WorkspaceBlock)=>WorkspaceBlock):WorkspaceBlock[]{let changed=false;const next=blocks.map((block)=>{if(block.instanceId===instanceId){changed=true;return updater(block);}let sectionChanged=false;const nextSections=block.sections.map((section)=>{const updatedBlocks=updateWorkspaceBlockTree(section.blocks,instanceId,updater);if(updatedBlocks!==section.blocks){changed=true;sectionChanged=true;return {...section,blocks:updatedBlocks};}return section;});return sectionChanged?{...block,sections:nextSections}:block;});return changed?next:blocks;}
export function setWorkspaceBlockComment(blocks:WorkspaceBlock[],instanceId:string,comment:string){return updateWorkspaceBlockTree(blocks,instanceId,(block)=>({...block,comment:comment.trim()?comment:undefined}));}
export function updateWorkspaceBlockParameter(blocks:WorkspaceBlock[],instanceId:string,parameterId:string,value:string){return updateWorkspaceBlockTree(blocks,instanceId,(block)=>({...block,parameters:block.parameters.map((parameter)=>parameter.id===parameterId?{...parameter,value}:parameter)}));}
export function insertWorkspaceBlockTree(blocks:WorkspaceBlock[],target:WorkspaceDropTarget,block:WorkspaceBlock){return insertIntoWorkspace(blocks,target,block)||blocks;}
export function moveWorkspaceBlockTree(blocks:WorkspaceBlock[],instanceId:string,target:WorkspaceDropTarget){const lookup=findWorkspaceBlock(blocks,instanceId);if(!lookup){return blocks;}if(target.parentInstanceId&&workspaceSubtreeContains(lookup.block,target.parentInstanceId)){return blocks;}const detached=detachWorkspaceBlockInternal(blocks,instanceId);if(!detached.removed){return blocks;}const adjustedTarget=detached.parentInstanceId===target.parentInstanceId&&detached.sectionId===target.sectionId&&detached.index<target.index?{...target,index:target.index-1}:target;const inserted=insertIntoWorkspace(detached.nextBlocks,adjustedTarget,detached.removed);return inserted||blocks;}
function duplicateWorkspaceStackInList(blocks:WorkspaceBlock[],instanceId:string):WorkspaceBlock[]|null{const index=blocks.findIndex((block)=>block.instanceId===instanceId);if(index>=0){const duplicates=blocks.slice(index).map((block)=>cloneWorkspaceBlock(block));const next=[...blocks];next.splice(index+1,0,...duplicates);return next;}for(const block of blocks){let sectionChanged=false;const nextSections=block.sections.map((section)=>{const duplicatedBlocks=duplicateWorkspaceStackInList(section.blocks,instanceId);if(!duplicatedBlocks){return section;}sectionChanged=true;return {...section,blocks:duplicatedBlocks};});if(sectionChanged){return blocks.map((item)=>item.instanceId===block.instanceId?{...item,sections:nextSections}:item);}}return null;}
export function duplicateWorkspaceStack(blocks:WorkspaceBlock[],instanceId:string){return duplicateWorkspaceStackInList(blocks,instanceId)||blocks;}
export function createStarterWorkspace(){const starterIds=["event-flag","motion-move","looks-say","control-stop"];return starterIds.map((id)=>blockCatalog.find((block)=>block.id===id)).filter((block):block is BlockCatalogEntry=>Boolean(block)).map((block)=>createWorkspaceBlock(block));}
